AllCops:
  Exclude:
    - bin/**/*
    - Gemfile
    - config/routes.rb
    - test/**/*
    - db/**/*
Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

  Max: 100

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes # hoặc xóa hoàn toàn tùy chọn này

Style/MethodDefParentheses:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true
